### ISSUE TITLE
ContentItemPreviewPanel - Incorrect behavior when clicking on links in the  preview panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#105]
1. Open `Features `and insert url-link into the` Hello World ` text-component
2. Select `Features `in the grid and click on the link in the `PreviewPanel`

**Issue:**
error appears in the browser console when clicking on link that  was inserted in a text-component

![step2](https://user-images.githubusercontent.com/3728712/39916360-e8aff598-5512-11e8-944f-c3a56752dbf9.png)

![result](https://user-images.githubusercontent.com/3728712/39916351-e2d2b02a-5512-11e8-89c9-57937fbf3b03.png)

**Comment by ashklianko** [comment]
This a google specific error, they set "x-frame-options: SAMEORIGIN" header so it can only be loaded from iframe "can only be displayed in a frame on the same origin as the page itself".

If you open content in preview google link works.

So to summarize: sites will be opening in ContentItemPreviewPanel if x-frame-options header is not set and this is not something we control.
