### ISSUE TITLE
Hide dependant items in the Duplicate dialog if it's already selected as a main item

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#132]
1. Select a site (A) and one of its child content items (B)
2. Open the Duplicate dialog

Both A and B have toggler icons "on" and the list of dependent items doesn't contain B - correct

3. Now click the toggler icon for "B"

Now B appears in the list of dependant items which is wrong because it's already included at the top list, so it's listed and counted twice.

**Comment by vbradnitski** [comment]
pushed to https://github.com/enonic/app-contentstudio/tree/issue-6260
