### ISSUE TITLE
FF specific bug. New Content Dialog - 'Recently Used' block is not displayed on the dialog, when it opened in first time

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#139]
1. Start FF an open `Content Studio`
2. Click on `New ` button

**Bug**: 'Recently Used' block is not displayed 
![image](https://user-images.githubusercontent.com/3728712/40367395-f5e0adde-5de1-11e8-9164-eb6529ce5baf.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #570](https://github.com/enonic/lib-admin-ui/issues/570) via [**ZenHub**](https://www.zenhub.com/)
