### ISSUE TITLE
Issue dialog - impossible to add more than 5 assignees

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#144]
1. Open a issue , open `IssueDetailsDialog `and add 10 users in 'assignees ' tab
2. Close the dialog and open the  issue in `IssueDetailsDialog  `again .
3. Go to `Assignees `tab 
**BUG**: Expected - 10 users should be present in the list
         Actual -      5 Users are present

![image](https://user-images.githubusercontent.com/3728712/40421319-2e137de6-5e94-11e8-9a71-d2af38220c30.png)

**Comment by pmi** [comment]
Must've been fixed by #169
