### ISSUE TITLE
Remove issueId from url after closing issue details dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#150]
Issue Details Dialog appears when refreshing the browse panel in browser.

1. Open Content Studio
2. Click on `Issues List` button and create a issue (just type a title )
3. Click on 'Close' button on the modal dialog
4. Refresh BrowsePanel in the browser

Bug: issue details dialog appears when the panel has been refreshed. Dialog appears because URL contains   ID of the issue 

![image](https://user-images.githubusercontent.com/3728712/40430401-be09bd0c-5ead-11e8-8ea1-185bb66604c0.png)

URL should be updated, when the modal dialog has been closed

**Comment by alansemenov** [comment]
The bug is not that the dialog appears when you refresh the page but that when the details dialog is closed we don't remove issueId from the url.
