### ISSUE TITLE
Duplicate Dialog - Incorrect number of duplicated items is displayed in  Notification Message

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#159]
1. Select 2 sites in grid
2. Click on `Duplicate`  - 74 items for duplicate 

![image](https://user-images.githubusercontent.com/3728712/40647448-8f4d2a36-6334-11e8-81e9-c4a864682719.png)

3. Click on Duplicate  button on the modal dialog

Bug: incorrect number is displayed in notification message

![image](https://user-images.githubusercontent.com/3728712/40647639-06a3b9ce-6335-11e8-9efb-070647677aa0.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp #6287](https://github.com/enonic/xp/issues/6287) via [**ZenHub**](https://www.zenhub.com/)
