### ISSUE TITLE
Handle exception when trying to save page as a template and '_templates' folder does not exist

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#161]
This issue appears when  '_templates' folder was **deleted** or site was **duplicated** without the folder
`Steps`: 
1 Open the site 
2. Press the `Save as Template` button

![image](https://user-images.githubusercontent.com/3728712/40649461-a73ca8d8-6339-11e8-8ca0-a514dd5a773b.png)

**Comment by alansemenov** [comment]
Catch the error and show our standard floating error message: "Failed to save the template"
