### ISSUE TITLE
Templates folder should be created automatically, when a site was duplicated

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#173]
1. Select  Features
2. Press Duplicate button
3. Click on `Exclude child` icon and press Duplicate button on the modal dialog

Expected:  _templates folder should be created in the duplicated site

**Comment by alansemenov** [comment]
Same logic as when user creates a new site - we create "_templates" folder automatically.

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp #6295](https://github.com/enonic/xp/issues/6295) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sigdestad** [comment]
Why? Let's not do this...

**Comment by alansemenov** [comment]
Two reasons:
1) To be consistent with the functionality of creating a new empty site
2) If the site is created without a templates folder, user has to create it manually to be able to add page templates. For some strange reason, we always look for page templates in a folder called "_templates" (I guess it's hardcoded in the server-side code somewhere). There's **no way** a user will figure out that he has to call the template folder "_templates" if he has to create it manually.

The whole concept of storing page templates in a folder which is its own content type and can easily be modified and deleted is very strange, but that's a different story. Here we should at least make sure that a duplicated site remains useable.

**Comment by sigdestad** [comment]
I get what you are thinking about, but this is overdesign when it comes to duplicate. Duplicate is not _create_.  For 99% of the cases when people duplicate a site, they will duplicate "everything". 

Also, I have suggestions for how to handle templates differently in the future....

Let's not waste time to implement this?

**Comment by alansemenov** [comment]
Let's not, but then we have to fix it so that we're looking for templates in the hardcoded "_templates" folder. Otherwise a duplicated site is pretty much unusable.

**Comment by sigdestad** [comment]
Yes, let's discuss this.
