### ISSUE TITLE
Update text of notifications messages

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#19]
@sgauruseu commented on [Mon Apr 09 2018](https://github.com/enonic/xp-apps/issues/754)

Currently we can see the next types of notification messages:

1. Content created       **actual**:  "Content created."      **expected**:   "Content is created."
2. Content Saved          **actual**:    ""display name" saved."     **expected** : The item is saved."
3. Content has been published **actual**:    "Item "/test" was published."    **expected**:   "The item is published."
4. Content has been unpablished  **actual**:     "Item "test" was unpublished."        **expected**: "The item is unpublished."
5.  Three items has been published **actual**:   "Published 3 items."     **expected**:  "3 items are published"

**Comment by pmi** [comment]
@alansemenov Is it a good idea to show less info than we can ? Also when operation results are mixed the message gets more complicated with further details.

**Comment by pmi** [comment]
Issue moved to [enonic/xp #6227](https://github.com/enonic/xp/issues/6227) via [**ZenHub**](https://www.zenhub.com/)
