### ISSUE TITLE
Content Wizard - owner is not selected in Settings, when the content was imported

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#213]
1. Click on 'Large tree'-  `by anonymous` is present on the grid-ttolbar
2. Open the folder
BUG: Owner is not selected in Settings

![image](https://user-images.githubusercontent.com/3728712/41278975-eab7eef6-6e33-11e8-9e62-0500cb0fbd9e.png)

in Wizard:

![image](https://user-images.githubusercontent.com/3728712/41279254-a56f2778-6e34-11e8-9cd8-5d18aaddd574.png)

**Comment by alansemenov** [comment]
@sgauruseu this is not a bug. what we show in the toolbar is last modifier, not owner.
