### ISSUE TITLE
ContentWizard Tooltip for Save button stays visible, when the button has been pressed and content saved

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#227]
1. Open wizard, type a data
2. Move cursor to `Save `button, tooltip message appears(OK)
3. Press the `save ` button 
Bug: the content is saved , but tooltip is still visible

![image](https://user-images.githubusercontent.com/3728712/41398681-c2dfcb5e-6fc0-11e8-9be2-2a1d7a666c74.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #596](https://github.com/enonic/lib-admin-ui/issues/596) via [**ZenHub**](https://www.zenhub.com/)
