### ISSUE TITLE
CreateIssue Dialog - assignees are not saved when users were added to group with required roles  

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#230]
1. Create a group with roles:
![image](https://user-images.githubusercontent.com/3728712/41401772-5dccee50-6fc9-11e8-8ae1-3208f8b0b037.png)
2. Add  some users and add  these users to the group 
3. Open `Create Issue dialog ` and assign an user that is added to the group
4. Click on `Create Issue` button
Bug:  user was not saved in assignees:

![image](https://user-images.githubusercontent.com/3728712/41401446-921537f4-6fc8-11e8-8251-f641e72feac2.png)

**Comment by pmi** [comment]
Issue moved to [enonic/xp #6357](https://github.com/enonic/xp/issues/6357) via [**ZenHub**](https://www.zenhub.com/)
