### ISSUE TITLE
Publishing Wizard dialog - Create Issue dialog does not appear when ' Create Issue..' menu item has been clicked

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#253]
1. Select a 'new' folder, press the Publish button(toolbar)
2. Open Publish-menu in the modal dialog and click on `Create Issue...`

Bug: Create Issue dialog should be loaded
Actual : error appears in the console 

![image](https://user-images.githubusercontent.com/3728712/41587308-94ab4812-73b7-11e8-9804-19e72360a830.png)

**Comment by pmi** [comment]
Fixed by #248
