### ISSUE TITLE
ContentWizard - toolbar is collapsed

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#265]
1. open an existing folder or open new wizard for folder, shortcut...

Bug: toolbar is collapsed

![image](https://user-images.githubusercontent.com/3728712/41765100-c2f6786c-760b-11e8-96bb-c83733a22c7d.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #634](https://github.com/enonic/lib-admin-ui/issues/634) via [**ZenHub**](https://www.zenhub.com/)
