### ISSUE TITLE
Wizard Step navigator is partially visible in collapsed mode

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#268]
1. Create a new site
2. Assign Superhero app
3. Select any controller
4. The Wizard panel will automatically collapse to give space to the PageEditor and the collapsed wizard step navigator will look like this:

![image](https://user-images.githubusercontent.com/11612490/41767576-4d0665aa-760a-11e8-8c1f-6121edd738cb.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #643](https://github.com/enonic/lib-admin-ui/issues/643) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alansemenov** [comment]
Ok, this is not entirely fixed. It seems to work if you open the Wizard and collapse the form manually, but try this:
1. Select Features site
2. Add new content, for example Html area
3. Fill out display name, click the icon in the top right corner to expand the page editor
4. Select any controller, for example Default
5. The wizard form will auto collapse and the step selector looks wrong

![image](https://user-images.githubusercontent.com/11612490/42022514-cbbd4d0c-7abd-11e8-8db5-edb9a2e5ec1d.png)
