### ISSUE TITLE
Applications and Users links should not be present on the LauncherPanel, when an  user has no Administrator role

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#27]
@sgauruseu commented on [Tue Mar 13 2018](https://github.com/enonic/xp-apps/issues/690)

1. Create a user with roles:  **Content Manager App,Administration Console Login, Content Manager Administrator**.

2. Login the user
BUG: Applications and Users link should not be displayed on the LauncherPanel

**Comment by alansemenov** [comment]
@sgauruseu I believe this was fixed. Please check

**Comment by edloidas** [comment]
@alansemenov @sgauruseu I can confirm that it is fixed now.
