### ISSUE TITLE
Inconsistent item count in content Duplicate and Delete dialogs

### ISSUE THREAD

**Issue by aro** [enonic-archive/app-contentstudio-old#275]
- Select the Features site
- Click duplicate. The dialog button shows "Duplicate (95)"
- Select the duplicated Features site
- Click on delete. The dialog button shows "Delete (127)"

One of the counts must be wrong.

![Screen Shot 2018-06-26 at 13.41.41.png](https://images.zenhubusercontent.com/58abfb4351aa2c305775002c/0c97f751-3df6-47e2-b7ca-d9f62ddcc4be)
![Screen Shot 2018-06-26 at 13.40.41.png](https://images.zenhubusercontent.com/58abfb4351aa2c305775002c/f208a0fe-951e-410e-9f47-1c5e6abd5d99)

**Comment by aro** [comment]
I cannot reproduce it neither on a clean installation. Looks like I had some corrupted data after importing data in older versions. It can be closed.

**Comment by sigdestad** [comment]
What is wrong here? The numbers look good to me?
Anyway, for both duplicate and delete it should not say "dependent" but child items imho.
