### ISSUE TITLE
Toolbar actions are always folded in the Content Wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#279]
This bug is reproduced on Windows OS
1. Set browser size  to 480x800 
2. Go to Content Studio and open new Folder wizard

**Bug**: toolbar is collapsed:

![image](https://user-images.githubusercontent.com/3728712/42026816-ca90964c-7ad0-11e8-80d2-ef8549a45180.png)

**Comment by alansemenov** [comment]
We should also make sure that the Content Studio icon to the left is never "swallowed" by the fold icon.  As of now, all of the tools inside the toolbar will be folded but we should be able to specify "unfoldable" elements, or fold only elements that are placed **after** the fold button.
