### ISSUE TITLE
Add ability to close or remove all issues, when linked content were removed 

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#312]
I have deleted all content in Grid, but `38 issues `  still present

![image](https://user-images.githubusercontent.com/3728712/42565912-7b433f6c-850d-11e8-81f5-166dba3b6ddd.png)

**Comment by alansemenov** [comment]
@sgauruseu this number represents the number of **issues** and doesn't have anything to do with content items. as long as you have 38 issues in the list when you open the dialog, everything is correct
