### ISSUE TITLE
Issue Detail Dialog - Tooltip stays  when the dialog has been escaped

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#314]
1. Open Issue Details Dialog , move cursor to the Comment link
Tooltip appears(OK)
2. Press `Esc` key twice and close modal dialogs
Bug - modal dialog has been closed, but tooltip is still visible 

![image](https://user-images.githubusercontent.com/3728712/42577083-76755b7c-852c-11e8-98f0-e2ee78e1324f.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #768](https://github.com/enonic/lib-admin-ui/issues/768) via [**ZenHub**](https://www.zenhub.com/)
