### ISSUE TITLE
Move Dialog - error message appears when try to move a content in the second time

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#317]
1. Add a new folder and move it to Features
2. Expand Features, select the folder and press Move
 
![image](https://user-images.githubusercontent.com/3728712/42635497-e5f6874c-85ee-11e8-9ad1-929b8ff93cf9.png)

**Comment by alansemenov** [comment]
@sgauruseu check if this one is still relevant

**Comment by sgauruseu** [comment]
This issue is fixed in:

https://github.com/enonic/app-contentstudio/issues/361
