### ISSUE TITLE
Edge specific bug - 'null' appears in the description-text area, when a site has been saved

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#35]
@sgauruseu commented on [Thu Feb 08 2018](https://github.com/enonic/xp-apps/issues/558)

1. Open XP in Edge browser, open wizard for new site
2. Type a name and click on Save
Bug: 'null' appears in the Description text area
Click on close browser-tab button, Save Before Close dialog appears

![descr](https://user-images.githubusercontent.com/3728712/35971766-8d0101be-0ccf-11e8-80bd-88dbe40cef05.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #601](https://github.com/enonic/lib-admin-ui/issues/601) via [**ZenHub**](https://www.zenhub.com/)
