### ISSUE TITLE
ItemSet content with Htmlarea - htmlarea is getting disabled when swap 2 items

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#360]
1.Open wizard for itemSet content, type a name. (ItemSet 0:0 with textline and htmlarea should be added before the creating the content)
2. Click on Add ItemSet 
3. type a text in both htmlArea
4. Click on Save button
5. drag a area and swap the areas
Bug - one pf the area is getting empty and disabled.

![image](https://user-images.githubusercontent.com/3728712/43712179-06e2a47a-997e-11e8-9801-2be6c571779f.png)

**Comment by sgauruseu** [comment]
`
item-set name="myItemSet"
      l
        input name="textLine" type="TextLine"
          label TextLine  label
          occurrences minimum="1" maximum="1"
        input
        input name="myHtmlArea" type="HtmlArea"
       
          occurrences minimum="1" maximum="1"
        input
      items
      occurrences minimum="0" maximum="0"
    item-set
`

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #759](https://github.com/enonic/lib-admin-ui/issues/759) via [**ZenHub**](https://www.zenhub.com/)
