### ISSUE TITLE
Incorrect behavior of selection in grid - last selected item should be displayed in the preview panel

### ISSUE THREAD

**Issue by ashklianko** [enonic-archive/app-contentstudio-old#362]
@sgauruseu commented on [Fri Aug 03 2018](https://github.com/enonic/lib-admin-ui/issues/739)

This bug is  reproduced  when you select more than 10 previewable contents.
1. Click on checkbox and select 10  items in the grid (site or image)
2. Click on one more checkbox
BUG : 11th item should be displayed in the preview-panel
Actual - 10th item is displayed

![image](https://user-images.githubusercontent.com/3728712/43634949-42b0f20a-9716-11e8-89fd-0eaab04f7621.png)

The similar issue, when you select more than 10 items in the grid and then unselect the last item
Site is unselected, but it still present in the preview panel.

![image](https://user-images.githubusercontent.com/3728712/43634638-563b1fb8-9715-11e8-85c9-14b9e5f63fb7.png)

---

@ashklianko commented on [Tue Aug 07 2018](https://github.com/enonic/lib-admin-ui/issues/739#issuecomment-411095079)

We have a restriction to 10 items for preview: 
PreviewContentHandler.BLOCK_COUNT is set to 10

@alansemenov do we need to update it?

---

@alansemenov commented on [Tue Aug 07 2018](https://github.com/enonic/lib-admin-ui/issues/739#issuecomment-411100229)

This is not the same thing. The limit of 10 prevents opening more than 10 new tabs with content preview simultaneously. This has nothing to do with the preview panel. 

> On 7 Aug 2018, at 17:20, Alex Shklianko <notifications@github.com> wrote:
> 
> We have a restriction to 10 items for preview:
> PreviewContentHandler.BLOCK_COUNT is set to 10
> 
> @alansemenov do we need to update it?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sigdestad** [comment]
I guess user should get a message saying "max 10" at least, otherwise no need to change imho.
