### ISSUE TITLE
Grid is not refreshed when switching between Inbound and Outbound dependencies

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#371]
1.  Add a content with Inbound and Outbound:
    For example:
     - create a site, select Features, insert an Image, save the image as fragment
     - create a template, select `site` in support, and insert the just created  fragment
2. select the fragment-content in the grid, and open `dependencies`
3. Click on `Show Inbound` button

![image](https://user-images.githubusercontent.com/3728712/44386627-bb56ba00-a52b-11e8-885a-ef2c42616fed.png)

Template is filtered in the grid (OK)

4. Click on "Show Outbound" button

**Expected**: Only Image should be  present in the grid

**Actual**: the template still present in the grid

**Comment by alansemenov** [comment]
Will be fixed by https://github.com/enonic/app-contentstudio/issues/376
