### ISSUE TITLE
New Content - Go directly to Wizard when there's only one content type available

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#38]
@alansemenov commented on [Tue Nov 21 2017](https://github.com/enonic/xp-apps/issues/274)

Very often there's only one content-type available in the New Content dialog in which case it becomes a redundant (and confusing) step that we should skip. Go directly to the Wizard in this case, skipping the dialog entirely.

![image](https://user-images.githubusercontent.com/11612490/33068384-65dca892-ceb1-11e7-9f04-b6f2914ac7b0.png)

---

@sigdestad commented on [Tue Nov 21 2017](https://github.com/enonic/xp-apps/issues/274#issuecomment-346042157)

Not sure where you got this task Alan - was it NAV? I'm worried about the consistency of our UI if we do this without thinking a bit more about things?

---

@alansemenov commented on [Tue Nov 21 2017](https://github.com/enonic/xp-apps/issues/274#issuecomment-346055048)

This was discussed several times before as a part of "New content" dialog not being easy to use dialog which popped up many times on discuss. I just made it as my own backlog to not forget it. Very irritating having to see this dialog every time when creating a new page template for example.

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #5](https://github.com/enonic/app-contentstudio/issues/5) via [**ZenHub**](https://www.zenhub.com/)
