### ISSUE TITLE
Show a tooltip with content type key in the Search Filter

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#39]
@alansemenov commented on [Tue Mar 20 2018](https://github.com/enonic/xp-apps/issues/703)

![image](https://user-images.githubusercontent.com/11612490/37659167-8b986d54-2c4f-11e8-8608-2a6dff505ac2.png)

https://enonic.zendesk.com/agent/tickets/2377

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #681](https://github.com/enonic/lib-admin-ui/issues/681) via [**ZenHub**](https://www.zenhub.com/)
