### ISSUE TITLE
Dependent items should by default be collapsed in modal dialogs

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#40]
1. Open CS, select Features, press the Delete button
`Show dependent items` link is displayed (OK)
2. Click on the link, then click on `Cancel` button
3. Open the dialog again
**Expected:**  `Show dependent items` link should be displayed

**Actual:** 
![del](https://user-images.githubusercontent.com/3728712/38989557-f071388a-43df-11e8-9420-df86287fa00e.png)

**Comment by alansemenov** [comment]
This is not a bug. In some dialogs we want user to instanly see the list of dependencies, and Delete dialog is one of such.
