### ISSUE TITLE
Remove icons from static wizard steps

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#423]
![image](https://user-images.githubusercontent.com/11612490/45609147-eebb3480-ba56-11e8-86a0-65e288de285c.png)

Icons in the toolbar should remain like now.

**Comment by ashklianko** [comment]
@alansemenov , what about Schedule step?

**Comment by sigdestad** [comment]
Same thing, remove icon there too

**Comment by alansemenov** [comment]
Yep, that too

**Comment by ashklianko** [comment]
Did it that way, already in PR
