### ISSUE TITLE
Incorrect handling of  Enter key event in NewContentDialog and InstallAppDialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#425]
1. Do 'Log out' , then do 'log in'
2. Go to Content Studio
3. Press the New an open   NewContentDialog
4. press `Enter`

Bug: `Launcher panel`  appears, when `Enter` has been pressed
Press `Esc` key,  `Launcher panel` closes, but the modal dialog remains on the grid-page

![image](https://user-images.githubusercontent.com/3728712/45616572-88dfa480-ba78-11e8-8043-98075b5debf4.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-users/issues/129

**Comment by alansemenov** [comment]
@sgauruseu I cannot reproduce this

**Comment by ashklianko** [comment]
I'll try with @sgauruseu

**Comment by sgauruseu** [comment]
This bug reproducing, when dialog is opened and  focus is not in the Search Input.
So, this bug does not always reproduce,.
I think, this issue similar to  
https://github.com/enonic/app-contentstudio/issues/427

**Comment by sgauruseu** [comment]
focus is not in Search Input of the dialog, when content-grid was refreshed before,

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #19](https://github.com/enonic/app-contentstudio/issues/19) via [**ZenHub**](https://www.zenhub.com/)
