### ISSUE TITLE
Modal Dialog - Pressing Enter on focused Cancel button propagates event to the grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#426]
The same issue in **Duplicate Dialog**, **Move Dialog**, **Sort Dialog**
1. Select `Features`
3. Open `Details Panel` and click on `Edit Permission`
3. press Tab key and move focus to the `Cancel`
4. Press the `Enter`

Expected: modal dialog should be closed
Actual: Features is opened in a wizard page

![image](https://user-images.githubusercontent.com/3728712/45616803-33f05e00-ba79-11e8-916b-e9bfee6e7dfe.png)

**Comment by ashklianko** [comment]
Fixing in https://github.com/enonic/app-users/issues/129

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/pull/819
