### ISSUE TITLE
Site Configurator Dialog - focus should be moved to the first enabled input

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#427]
1. Open existing site (Superhero)
2. Open `Site Configurator`  modal dialog

Bug: 
Actual - Focus is on the wizard toolbar
Expected - Focus should be moved to the modal dialog

![image](https://user-images.githubusercontent.com/3728712/45617792-1e306800-ba7c-11e8-92ce-82aa12fcd0e1.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #824](https://github.com/enonic/lib-admin-ui/issues/824) via [**ZenHub**](https://www.zenhub.com/)
