### ISSUE TITLE
Image, that was inserted in text component should be present in the site's Outbound dependencies

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#439]
1. Open `Features` and insert a text component
2. Insert an image in the text component, save all
3. Go to the grid, select `Features`, open Dependencies panel.

**Bug**
- Image that was inserted, should be present in Outbound dependencies.
- Select the image in the grid and press  `Delete` button. 
Expected warning should appears:
![image](https://user-images.githubusercontent.com/3728712/45871228-9e650f00-bd95-11e8-80c1-5306cc3fe243.png)

Error in console appears when the image has been deleted

![image](https://user-images.githubusercontent.com/3728712/45870792-73c68680-bd94-11e8-9740-caeeaf8b0156.png)

**Comment by alansemenov** [comment]
This is currently not possible, but will start working after https://github.com/enonic/xp/issues/6452 is implemented - when we will correctly parse and store references inside HTML Area.
