### ISSUE TITLE
Content Wizard - Save button for modified content should not become disabled after publishing in another tab

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#463]
1. Open new wizard for content with required input(Image-selector 2:4)
2. Type a name and select 2 images, save the content.
3. Remove one required image, but do not save the content.
4. Go to content-grid, select the content and press `Publish` button, then do publish it in the dialog. 
5. Go to the wizard 
**Bug  - content was saved and published but it is not valid in the wizard** 

![image](https://user-images.githubusercontent.com/3728712/46476334-9030dd00-c7f0-11e8-9dbc-c4d147da7633.png)

**And this content is valid in the grid :**

![image](https://user-images.githubusercontent.com/3728712/46476492-01709000-c7f1-11e8-87a9-27ea3a597dc3.png)

**Comment by alansemenov** [comment]
The good news is that when the content was published, it published the valid version while it still had required field values. The bug here is that Content Wizard is acting as if it saved the content, even though it didn't. I'll change the title of this bug.
