### ISSUE TITLE
Site Wizard - 'Save' button gets enabled after rollback to a version with no application assigned

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#481]
1. Open new site-wizard, type a name and save it 
2. Select `Features` in  the wizard and save it 

![image](https://user-images.githubusercontent.com/3728712/46796071-5f065e80-cd54-11e8-8dde-455fd94d6f94.png)

3. Open Version history panel and rollback the version, when application is not selected yet.

Bug:  `Save` button is getting enabled, 'Save Before Close' dialog appears, when try to close the wizard

![image](https://user-images.githubusercontent.com/3728712/46796193-b278ac80-cd54-11e8-8972-b96469dc2e8d.png)

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #22](https://github.com/enonic/app-contentstudio/issues/22) via [**ZenHub**](https://www.zenhub.com/)
