### ISSUE TITLE
Page Editor  - broken layout in image selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#489]
1. Open new  child content in Features, 
2. Insert Image Component in page editor 

Bug:  layout is broken 

 
![image](https://user-images.githubusercontent.com/3728712/46946372-30ec8b80-d080-11e8-9f3d-f3f46a4a29b7.png)

**Comment by alansemenov** [comment]
@edloidas Looks like CSS from ``inputtype/selector/content-combo-box`` is missing in page-editor's ``all.css``
