### ISSUE TITLE
Content Studio - Set content name as unnamed

### ISSUE THREAD

**Issue by GlennRicaud** [enonic-archive/app-contentstudio-old#5]
* Create a content
* Name it '__unnamed__d4bc2026-0703-4147-82bc-cbf414eb18c5'(name, not only display name)
* Save it
* Close the Edit tab
=> Problem 1: We get proposed to save the content (It is supposed to be saved)
* Inspect the content with Content Viewer:
=> Problem 2: The name is '\_\_unamed\_\_'. This is not what was displayed and wanted

**Comment by ashklianko** [comment]
This is because content name is treated as unnamed when it's name consists of '__unamed__' part

**Comment by ashklianko** [comment]
Possibly fixed in https://github.com/enonic/xp/pull/6335, will check when merged

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #603](https://github.com/enonic/lib-admin-ui/issues/603) via [**ZenHub**](https://www.zenhub.com/)
