### ISSUE TITLE
Save button for unchanged content in the Wizard gets enabled after server update

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#532]
1. Open Wizard for the Features site. Note that "Save" button is disabled.
2. Switch back to the grid
3. Open the Permissions modal dialog for the Features site from the Detail panel.
4. Change permissions and apply the changes
5. Switch to the Wizard tab - the Save button is enabled.

**Comment by vbradnitski** [comment]
fixed in https://github.com/enonic/app-features/commit/d8139f32f189162ea2ff5452d0d54c1df42acd1e

**Comment by alansemenov** [comment]
The original issue is fixed, but now the Features site is created with invalid icon displayed in the grid (not in the Wizard).

**Comment by vbradnitski** [comment]
fixed in https://github.com/enonic/app-features/commit/c95761694974e75775d6e29f4b264d2dbb01108e
