### ISSUE TITLE
Delete Content dialog - Progress bar is not updated during delete operation

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#537]
1. Open Content Studio
2. Select some content with lots of children - "Large Tree" from the Features app is good (208 items total)
3. Open Delete Content dialog and press Delete

Progress bar appears and is visible for several seconds but it's not being updated while items are being deleted.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/xp #6743](https://github.com/enonic/xp/issues/6743) via [**ZenHub**](https://www.zenhub.com/)
