### ISSUE TITLE
Image Editor - Don't apply cropping on client-side

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#539]
There was a bug in [``ContentImageResource.java``](https://github.com/enonic/xp/blob/a7595e372fb3e656e7d1023bb72715e43aa6e65c/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageResource.java#L146) which results in cropping not being applied to image when ``source`` parameter is _true_ (orientation is correctly applied). Image Editor applies cropping client-side to get the right image. With the bug in ``ContentImageResource.java`` fixed, cropping is now applied twice - first by server-side service and second time client-side in the Image Editor. We need to remove the client-side processing since it's already done on the server-side.

"?source=true" mode is also used by HTML Area's Image dialog to serve the image without scaling, but it's important that metadata like orientation, cropping, focal point etc. is still used in this mode.

If the Image editor also needs the original image without meta-data we should implement a separate parameter/method in ``ContentImageResource``.

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #27](https://github.com/enonic/app-contentstudio/issues/27) via [**ZenHub**](https://www.zenhub.com/)
