### ISSUE TITLE
Content Wizard - Template info in the details panel is not updated after template is removed

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#550]
1. Create a site , 
2. expand the site and add a template for folder
3. Open wizard for new folder , type a name and save it , open in the wizard details panel for the folder .
4. Go to the grid and delete the template 
5.  Go to the folder wizard again 

**BUG**:  link for the deleted  template still present in  `Details Panel`, 

![image](https://user-images.githubusercontent.com/3728712/48768088-55640500-ecc9-11e8-8523-e1c1f49e2b21.png)

**if click on the link, error in console and notification will appear**

![image](https://user-images.githubusercontent.com/3728712/48768025-2483d000-ecc9-11e8-86cb-7e5b465c0812.png)

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #30](https://github.com/enonic/app-contentstudio/issues/30) via [**ZenHub**](https://www.zenhub.com/)
