### ISSUE TITLE
Sanitize binary names

### ISSUE THREAD

**Issue by GlennRicaud** [enonic-archive/app-contentstudio-old#569]
Binary names should be sanitized by Content Studio when uploaded
The list of illegal characters is: '/', '\', '*', '?', '|', ':'

![screen shot 2018-11-23 at 14 04 48](https://user-images.githubusercontent.com/12030113/48944966-fc92a780-ef28-11e8-83d8-390e0c1421d6.png)

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #33](https://github.com/enonic/app-contentstudio/issues/33) via [**ZenHub**](https://www.zenhub.com/)
