### ISSUE TITLE
ContentWizard - incorrect behavior when  permissions have been applied and content data is not saved yet 

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#570]
- **Incorrect behavior of validation in wizard** 
 1) open new folder wizard , type a name (do not save it ), then add one additional permission,
 2)  click on `Apply`

BUG: red icon appears on the wizard, content is invalid

![image](https://user-images.githubusercontent.com/3728712/49011165-986d1f00-f186-11e8-9694-0c909fd7e0ed.png)

- Selected application is cleared in the site wizard

1) Open new site-wizard, select `Features`
2) Do not save the site and open `Edit Permissions` dialog
3) Add new principal with default permissions
5) click on Apply

BUG: 
- selected  option in Applications is removed when new permissions has been applied

![image](https://user-images.githubusercontent.com/3728712/49011407-5d1f2000-f187-11e8-970f-390323478193.png)

**Comment by vbradnitski** [comment]
fixed by epic https://github.com/enonic/xp/issues/6785
