### ISSUE TITLE
ContentDeleteDialog - dependent items should be collapsed by default

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#574]
1. Select Features, click on Delete button
2. Click on `Show dependent items` link  in the dialog
3. Press the Cancel button(Dialog closes ) 
4. Click on Delete button on the toolbar

**Bug:** 
**Actual** : Dependent items  are expanded
![image](https://user-images.githubusercontent.com/3728712/49145445-d8600d80-f310-11e8-82fd-78531b8563a7.png)

**Expected**:  `Show dependent items` link  should be displayed

**Comment by alansemenov** [comment]
We've discussed this several times.... We show dependent items by default in this specific dialog because deleting items is a critical action and it's important that user can instantly see all the items that will be deleted.
