### ISSUE TITLE
HtmlArea content - broken layout after rollback a version with  scrollbar

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#591]
1. Select `Features` and open HtmlArea wizard
2. Type a name in the wizard, save it 
3. Go to `Second HTML content ` . Click on `Add` button and add one more html area. 
4. Insert an  image (see the screenshot) and save all

![image](https://user-images.githubusercontent.com/3728712/49379271-c4a51480-f71f-11e8-84cf-8081b335ace1.png)

5. Open `Versions` in the wizard and restore the previous  version 
6. Click on the htmlara that is below the area with the image 
7. Restore the version with the image again 

**Bug: Layout is broken** .   _Layout is getting normal after refresh the page in browser_

![scr1](https://user-images.githubusercontent.com/3728712/49379518-5745b380-f720-11e8-8649-64ad24c493b3.png)

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #34](https://github.com/enonic/app-contentstudio/issues/34) via [**ZenHub**](https://www.zenhub.com/)
