### ISSUE TITLE
Image Wizard - incorrect height of the Image Editor toolbar

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#622]
1. Open an existing image 
2. Do scroll the page 
Bug: height of the toolbar  is more then height of the 'wizard step'-  toolbar 

![image](https://user-images.githubusercontent.com/3728712/50078056-04c3c700-01f7-11e9-882d-6b3699301b3d.png)

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #38](https://github.com/enonic/app-contentstudio/issues/38) via [**ZenHub**](https://www.zenhub.com/)
