### ISSUE TITLE
Downloads selector in the Insert Link dialog is not limited to current site content

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#636]
1. Open a `site configurator`  dialog with htmlarea
2. Open Insert Link dialog and go to Downloads tab
3. Expand options in the  target-selector 

Bug - options are not limited to the site

![image](https://user-images.githubusercontent.com/3728712/50222847-8b6cd580-03aa-11e9-959c-6cfcd5637cfe.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/pull/673
