### ISSUE TITLE
Site Configurator Dialog - Error when inserting an image in "Insert Content Link" modal dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#637]
1. Open SuperHero, then open SiteConfigurator dialog
2. Click on `Insert Image` button  `Insert Image` dialog appears
3. Click on 'upload-button' and upload an image, click on `Insert` button then click on `Apply `

![image](https://user-images.githubusercontent.com/3728712/50227301-801fa700-03b6-11e9-8aff-cb4362ffe388.png)

**The image is inserted in htmlarea.**

4. Click bellow of inserted image and  click on **Insert Link** button and go to `Content tab` and select the  just uploaded image.
5. Type title and click on Insert button

Bug: error occurs and the dialog does not close

![image](https://user-images.githubusercontent.com/3728712/50223983-b1e04000-03ad-11e9-8bce-0f153ca30acb.png)

`_all.js:1 Uncaught TypeError: Cannot read property 'getSelection' of undefined
    at CKEDITOR.dom.selection.getNative (_all.js:1)
    at new CKEDITOR.dom.selection (_all.js:1)
    at a.CKEDITOR.editor.getSelection (_all.js:1)
    at a.elementPath (_all.js:1)
    at a.<anonymous> (_all.js:1)
    at a.p (_all.js:1)
    at a.<anonymous> (_all.js:1)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (_all.js:1)
    at a.setActiveFilter (_all.js:1)
    at n (_all.js:1)`

**Comment by ashklianko** [comment]
Tested with @sgauruseu , doesn't seem to reproduce with fix for https://github.com/enonic/app-contentstudio/issues/623.

Agreed with @sgauruseu that he'll test after https://github.com/enonic/app-contentstudio/issues/623 is merged.

**Comment by ashklianko** [comment]
Issue is rarely reproduced and on a very specific case;  Seems to occur somewhere deep in native CKE code;
I'll postpone for now as there other bugs to fix and investigating this takes too mmuch time.

**Comment by sgauruseu** [comment]
Probably this issue is linked with  https://github.com/enonic/app-contentstudio/issues/669
And a Caption is cause of the both issues. 
Try to upload an image with caption to reproduce  the #637

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #44](https://github.com/enonic/app-contentstudio/issues/44) via [**ZenHub**](https://www.zenhub.com/)
