### ISSUE TITLE
Insert Link dialog - selected option is not displayed on the dialog  when 'content link' was inserted

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#638]
1. Select Features and open a content with HtmlArea
2. Open 'Insert Link' dialog , click on `Content` tab 
3. type a title then select a target
4. Click on `Insert` button Dialog closes  . Link is inserted (OK)
5. Double click on the link
6. Insert link modal dialog is opened 

BUG: Expected  selected content is not present on the dialog   

![image](https://user-images.githubusercontent.com/3728712/50227800-a1cd5e00-03b7-11e9-9829-17648507813b.png)

**Comment by alansemenov** [comment]
@sgauruseu We need a test for this
