### ISSUE TITLE
Error notification message appears when Deleted content has been published

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#64]
1. Select a Deleted-content in the grid
2. Click on `Publish `button

Bug: error notification appears 

![image](https://user-images.githubusercontent.com/3728712/39517404-70acc3ca-4e08-11e8-8f90-d5e731b5c4d3.png)

**Comment by alansemenov** [comment]
@sgauruseu can you add more details here? when I simply delete and publish any content it works fine for me.

**Comment by pmi** [comment]
Issue moved to [enonic/xp #6327](https://github.com/enonic/xp/issues/6327) via [**ZenHub**](https://www.zenhub.com/)
