### ISSUE TITLE
Allow blockquote tag by default in CKEditor

### ISSUE THREAD

**Issue by ashklianko** [enonic-archive/app-contentstudio-old#671]
@Bellfalasch commented on [Fri Jan 04 2019](https://github.com/enonic/xp/issues/6846)

In TinyMCE we had the possibility to add `Blockquote` blocks for text as a default option. When upgrading to CKEditor this functionality is lost, and must be added manually everywhere HtmlAreas are used. Could this Blockquote button be added as standard in CKEditor? (while properly handle content types that now manually re-adds them?).

The reason this function fell out is that TinyMCE added it as an option in the `styleselect` whereas CKEditor adds it as a separate button.

---

@alansemenov commented on [Mon Jan 07 2019](https://github.com/enonic/xp/issues/6846#issuecomment-451947650)

@Bellfalasch not sure if this should really be a default option... it doesn't look like something that is used often and it can easily be added via config. have you received many complaints about it being missing?

---

@Bellfalasch commented on [Tue Jan 08 2019](https://github.com/enonic/xp/issues/6846#issuecomment-452231882)

Problem is that if you do not have this button, the editor will remove any `<blockquote>` when saving. So basically breaking/ruining articles created with TinyMCE. When button is added the html tag is kept. Pretty annoying yes.

---

@ashklianko commented on [Tue Jan 08 2019](https://github.com/enonic/xp/issues/6846#issuecomment-452234183)

We can adjust editor filter to not strip `blockquote`

---

@alansemenov commented on [Tue Jan 08 2019](https://github.com/enonic/xp/issues/6846#issuecomment-452255813)

Oh, I see. Yes, let's not add the button by default but make sure the tag is passed by the filter.

**Comment by sigdestad** [comment]
Hmm.. How are we doing this? Screenshots? Souldn't people rather use macro's for stuff like this?

**Comment by ashklianko** [comment]
At least via source dialog

**Comment by Bellfalasch** [comment]
`<blockquote>` is as basic as something like `<strong>` etc, and has been in the HTML spec almost since the beginning. I see no reason not having this by default. Even we use it a lot, like on these pages:
https://enonic.com/developer-tour/web-application-platform 
https://enonic.com/case-studies/norsk-toppfotball
... just to name a few. Building a macro for basic HTML-tags sounds like unnecessary hassle for something that already exists as a CKEditor button.
