### ISSUE TITLE
Broken layout for selected page in the Inspect panel

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#689]
![image](https://user-images.githubusercontent.com/11612490/50972841-e09e9180-14e7-11e9-8b03-177027a1a052.png)

**Comment by jsi** [comment]
Issue moved to [enonic/app-contentstudio #53](https://github.com/enonic/app-contentstudio/issues/53) via [**ZenHub**](https://www.zenhub.com/)
