### ISSUE TITLE
'Insert Special character' modal dialog must handle close on Esc

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#69]
1. Open a content with htmlArea
2. Click on `Insert Spec Chararcter` icon
3. Press `Esc` key, when dialog is opened

**Expected**: dialog should be closed

![image](https://user-images.githubusercontent.com/3728712/39573954-f46c0768-4edd-11e8-9f91-69a83069f845.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #476](https://github.com/enonic/lib-admin-ui/issues/476) via [**ZenHub**](https://www.zenhub.com/)
