### ISSUE TITLE
Add Context panel to the Content Wizard

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/app-contentstudio-old#96]
Show the detail panel icon to the right of the monitor icon toggling the Page Editor panel. It should expand/collapse the detail panel for current content just like it does for selected content in the Content Grid. Like in the Grid, should expand in floating mode on resolution < 1000px, otherwise docked mode.

![image](https://user-images.githubusercontent.com/11612490/39753563-974e4e52-52bf-11e8-8924-4f63c7056869.png)

In *mobile mode* it should behave the same as in the preview: the panel should slide in from the bottom up and slide out from the top down. Highlight the icon with blue color when the panel is expanded.

![issue-detail-panelv2 006](https://user-images.githubusercontent.com/11612490/39753692-fffae6ae-52bf-11e8-9352-91d071981f03.png)
![issue-detail-panelv2 007](https://user-images.githubusercontent.com/11612490/39753693-00119d04-52c0-11e8-8f3b-15313099b21f.png)

**Comment by alansemenov** [comment]
@pmi See comments in the PR

**Comment by pmi** [comment]
@ase Updated PRs

**Comment by pmi** [comment]
@ase Done ! 🎉
