### ISSUE TITLE
Impossible to move two or more text-fragments into the same folder

### ISSUE THREAD

**Issue by ashklianko** [enonic-archive/app-contentstudio-old#99]
@sgauruseu:
**Issue : Impossible to move two or more text-fragments into the same folder**, because all fragments that were made from a text-component have the same name : `fragment-text`,  so when you try to move the second text-fragment, error-notification message appears:
<img width="700" alt="i2" src="https://user-images.githubusercontent.com/3728712/38368855-14cab090-38ef-11e8-9ea4-ea4a4ca5e3a7.png">

**Steps to reproduce:**

1. Open a site, insert two text-components and create two fragments from the components
2. Try to move both fragments to the root directory
 

![image](https://user-images.githubusercontent.com/3728712/38370291-72ea3440-38f2-11e8-8d32-394c46725644.png)

**Comment by ashklianko** [comment]
@sgauruseu , 
This is not an issue of a text-component, you can't have equally named contents in same path.
@alansemenov do we need to handle name of a moved content in case content with such name already exists in target folder?

**Comment by sigdestad** [comment]
This is not a bug.. However, you should check that everything works fine if you create fragments form two different text components on a page (that must work)

**Comment by ashklianko** [comment]
That works fine
